# Generated by Django 4.1.4 on 2023-01-22 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('system_admin', 'Pode modificar o cardapio')]},
        ),
    ]
