# Generated by Django 4.1.4 on 2023-01-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_categoria_prato'),
    ]

    operations = [
        migrations.AddField(
            model_name='prato',
            name='descricao',
            field=models.TextField(default=None),
        ),
    ]
